### ISSUE TITLE
Support for Arc Browser

### ISSUE THREAD

**Issue by Leykwan132** [vercel/analytics#100]
I was testing my production website on Arc Browser, but the analytics seems not to show any information about Arc. What could be the possible catch here? ( Safari, Chrome, IOS all worked as expected)

**Comment by tobiaslins** [comment]
Hey! This is because Arc is based on Chromium so the `user-agent` is the same as Chrome. There are no plans to add support for manually detecting Arc at the moment

**Comment by Leykwan132** [comment]
I see. Thanks!
