### ISSUE TITLE
User Opt in feature

### ISSUE THREAD

**Issue by douglasrcjames** [vercel/analytics#101]
Is there a way for the user to "opt in" or "opt out" of enabling Vercel Analytics? We have this setup with Google Analytics to adjust whether data is collected or not based on the user accepting "cookies" when they enter the site. We need this to stay compliant with GDPR! If not, is this in the roadmap for the future?

**Comment by tobiaslins** [comment]
Hey @douglasrcjames !
Vercel Web Analytics is not collecting any PII and we're not using cookies and can't track sessions longer then 24 hours.

For that reason you don't need a cookie banner. More infos [here](https://vercel.com/docs/analytics/privacy-policy)

**Comment by douglasrcjames** [comment]
Awesome, thanks!
