### ISSUE TITLE
Can't use server track in Remix

### ISSUE THREAD

**Issue by JClackett** [vercel/analytics#111]
It seems the track function uses the "use-server" package and that fails to detect when running in a remix action apparently.

I've got a `analytics.server.ts` file which exports the track function from this package, ive added a "use server" line at the top but I still get:

```
Error: This module cannot be imported from a Client Component module. It should only be used from a Server Component.
```

Any ideas what I could be doing wrong?

p.s also had to add @vercel/analytics to remix's serverDependenciesToBundle config

**Comment by tobiaslins** [comment]
Hey!
Can you please provide us a minimal reproduction? Would love to dig into this

**Comment by JClackett** [comment]
Here it is, it's just a stripped back remix on vercel template that imports the analytics function from a .server file

https://github.com/JClackett/remix-vercel-analytics

the dev server won't even run because the "server-only" package throws an exception

**Comment by tobiaslins** [comment]
Thanks!
We're trying to figure out how remix works for bundling. seems like `server-only` package mostly just useful for Next.js

**Comment by tobiaslins** [comment]
We'll push the new release out today (`1.1.1`) which fixes the issue!
