### ISSUE TITLE
Error 400 when using analytics/server track in server actions

### ISSUE THREAD

**Issue by mtsdalmolin** [vercel/analytics#115]
## Error 400 when using analytics/server track in server actions
I am getting http error 400 on analytics when using analytics/server track in server actions.
Following the [documentation](https://vercel.com/docs/analytics/custom-events#tracking-a-server-side-event), this is the code snippet I am running:

```typescript
export async function getTeamStatistics(_: any, formData: FormData) {
  const teamId = formData.get('teamId')!
  const teamName = formData.get('teamName')!

  await track('action:getTeamStatistics', {
    teamId: teamId as unknown as string,
    teamName: teamName as unknown as string
  })
  ...
}
```

I haven't seen any custom event in my analytics page and the logs of the request is showing this:
![image](https://github.com/vercel/analytics/assets/33668259/74e41629-0720-4f38-b9ad-d4d25fb0322a)

No custom events in analytics page:
![no-custom-events](https://github.com/vercel/analytics/assets/33668259/c021abc2-5ad8-4afa-a61a-e3c41d2328b6)

Is there anything I am doing wrong?

P.S.: I made a [stackblitz](https://stackblitz.com/edit/stackblitz-starters-xsraq1?file=app%2Fpage.tsx) with a simplistic reproduction of the code I am running.

**Comment by tobiaslins** [comment]
Hey @mtsdalmolin !

sorry for the inconvenience. there were some issues for some deployments that are now fixed. can you please redeploy and try again? it should be working fine now! 🙂

**Comment by mtsdalmolin** [comment]
Yep, it's working now, @tobiaslins.
Sorry for bothering you guys here in github with this issue, I thought it was something I was doing wrong.
