### ISSUE TITLE
Vercel build failed with Turborepo and multiple apps deployed

### ISSUE THREAD

**Issue by johannpinson** [vercel/analytics#117]
Hello,

I got build error from Vercel with a turborepo config:

<img width="421" alt="image" src="https://github.com/vercel/analytics/assets/2202989/fb1fe168-b394-4742-aeae-afbef8c95178">

This is the partial repository organization, using npm workspaces combined to turborepo

```
- package.json (root pkg)
- packages-lock.json (contain the `@vercel/analytics` reference and all deps)
- node_modules/ (the uniq `node_modules` folder for all the workspace)
- apps/
  - web/ (Next 13.5.x)
    - package.json (contain the `@vercel/analytics` pkg, and others monorepo deps, ui, auth...)
  - docs/ (Storybook v7)
    - package.json (storybook deps + packages/ui)
- packages/
  - ui/ (react ui components)
  - ...
```

In fact, I don't need to add the analytics on the Storybook project, because it uses internally.

So do I need to move the `@vercel/analytics` package inside the root `package.json`?

**Comment by johannpinson** [comment]
Hey @feugy 

Thanks for your feedback, I also discuss with the Vercel support who confirm me the revert.
The new builds (and even redeploy) work well.

Feel free to close the issue or keep it as reference if needed 😉

**Comment by feugy** [comment]
Hi! 
Vercel CLI 32.6.1 has been deployed last Friday with a fix. I'll close this issue, feel free to reopen in case you have a related followup!
