### ISSUE TITLE
Vercel Analytics Endpoints

### ISSUE THREAD

**Issue by veloii** [vercel/analytics#118]
Vercel Analytics takes control of the `/_vercel/insights` endpoint even when analytics is disabled in the dashboard.

This seems to be caused when the `@vercel/analytics` package is installed. I understand this is a big ask, but I would greatly appreciate it if this could only happen when it is enabled in the dashboard. I'm creating an open-source library that has cross compatibility for the `@vercel/analytics` package and it would make the project possible as Vercel would not automatically reroute these endpoints.

I was recommended by Vercel Support to post an issue in this repository.

**Comment by tobiaslins** [comment]
Hey @veloii 

We're sorry about that. We don't have the intention to change that back as this allows our customers to have a even better onboarding experience.
