### ISSUE TITLE
Docs: Specify if `track` runs in development mode or not

### ISSUE THREAD

**Issue by jamesvclements** [vercel/analytics#119]
Does `track` still run when `NODE_ENV === development`? I'm wondering if I should wrap my `track` calls in `process.env.NODE_ENV ===` checks, or if this is handled automatically by the analytics library.

**Comment by tobiaslins** [comment]
Hey @jamesvclements !

It "runs" during development as well, you should see a `console.log`. 
We're not sending the event to the server during development
