### ISSUE TITLE
Page changes are no longer tracked in SvelteKit 2

### ISSUE THREAD

**Issue by mattpilott** [vercel/analytics#121]
Using @vercel/analytics with SvelteKit v2 only registers the initial page load and ignores all subsequent requests.

Followed the guide here: https://vercel.com/docs/analytics/quickstart

Implemented the inject function in layout.js, tried inside and outside the load function plus tried it in the layout.svelte file and all give the same result. The only way to get a navigation to register beyond the initial page load is to do a page reload

This means web analytics with SvelteKit 2 is currently of limited use and is largely broken

**Comment by mschmdb** [comment]
Experiencing the same

**Comment by hchris21** [comment]
It has nothing to do with SvelteKit, unfortunately I am using plain Next.js (latest version) and I am experiencing the same issues as described by @mattpilott. 

It will only recognise the route of the initial page load OR on a full refresh. 

I am using the `next/link` package for navigation.

**Comment by tobiaslins** [comment]
Hey @mattpilott 

This should be resolved by the SvelteKit patch you see linked above.

@hchris21  
This shouldn't happen. Can you share a domain with us so I can check? Soft navigations should be reported as expected for all frameworks

**Comment by hchris21** [comment]
Hey @tobiaslins, thanks for the reply. Here is the domain: https://www.hornxengineering.dev

**Comment by tobiaslins** [comment]
@hchris21  which Next.js version are you on?
did you add the Analytics component to the layout.tsx?

**Comment by hchris21** [comment]
@tobiaslins, on my latest build I am using Next.js `14.0.3`, and yes, the `Analytics` component is added inside the **root** `layout.tsx` as mentioned in the docs, like:

```js
<html lang="en">
   <body>
       <main>
          <Navbar /> // this is the component with the Links
          {children}
       </main>
       <Analytics />
   </body>
</html>
```

I have also tried it out with the `<Analytics />` being **inside** the `<main>` (together with the Navbar and children), but it did not make a difference

**Comment by hchris21** [comment]
Hey @tobiaslins, I have updated the dependencies and now it is showing the page views on my non-root pages as well.

I **assume** it has to do with the fact that the `next` version is now `14.0.4`, because the other deps that were updated were packages like: **autoprefixer, classnames, eslint-config-next, geist and tailwindcss**, I believe none of these packages have conflicted with the `Analytics`.

**Comment by tobiaslins** [comment]
For me it looks fine. On your page, /work gets tracked on navigating
<img width="360" alt="image" src="https://github.com/vercel/analytics/assets/2978876/a62cca3e-d27f-4dd0-9f88-8c52420ddfa5">

**Comment by tobiaslins** [comment]
Will close this here! feel free to reopen if there are other issues
