### ISSUE TITLE
Integration with Docusaurus

### ISSUE THREAD

**Issue by onattech** [vercel/analytics#126]
Is there a way to integrate vercel analytics with Docusaurus?

**Comment by tobiaslins** [comment]
Hey!

I think there are two ways you could achieve this using Docusaurus.

1. Adding a script tag 
Add our tracking script to `docusaurus.config.js` : https://docusaurus.io/docs/api/docusaurus-config#scripts
```
 scripts: [
    {
      src: '/_vercel/insights/script.js',
      defer: true,
    },
  ],
```


2. `Swizzling` your theme https://docusaurus.io/docs/swizzling#wrapper-your-site-with-root

There might be other ways to add it but I am not too familiar with docusaurus.

I hope that helps
