### ISSUE TITLE
Vercel Analytics being blocked by AdBlockers

### ISSUE THREAD

**Issue by bmarianome** [vercel/analytics#137]
I was using plausible with the next-plausible package and, proxying the request, it was able to track users with AdBlock or any other ad blocker

Since vercel/analytics sends the request to `/_vercel/insights/` it gets blocked by the adblockers or Brave for example

Is there a way to bypass the adblockers with this package?

Already tried with the rewrites in the vercel.json file
```
{
  "rewrites": [
    {
      "source": "/_vercel/insights/:slug",
      "destination": "/_vercel/data/:slug"
    }
  ]
}
```

**Comment by tobiaslins** [comment]
It's not recommended but take a look here: https://github.com/vercel/analytics/issues/102#issuecomment-1898654030

Hope it helps! :)
