### ISSUE TITLE
script.js doesn't load with Next.js Dyamic Routes? [Error on build only]

### ISSUE THREAD

**Issue by mitchuman** [vercel/analytics#144]
When using Next.js Dynamic Routes ([setup found here](https://github.com/nuotsu/sanitypress/blob/vercel-analytics/next/src/app/[slug]/page.tsx) and just below), `/_vercel/insights/*` does not seem to get included in the build, thus the analytics scripts aren't running.

Setup: `/app/[slug]/page.tsx`

Notice the usage of `notFound()` and `generateStaticParams()` that likely disable generated routes that aren't included in the fetched data, including /_vercel/*

```tsx
export default async function Page({ params }: Props) {
	const page = await getPage(params)
	if (!page) notFound()
	return <>...</>
}

export async function generateMetadata({ params }: Props) {
	const page = await getPage(params)
	if (!page) notFound()
	return { ... }
}

export async function generateStaticParams() {
	const slugs = await fetchData(...)
	return slugs.map((slug) => ({ slug }))
}
```

Local dev (no issue):  
<img width="1125" alt="Screenshot 2024-06-07 at 2 08 26 PM" src="https://github.com/vercel/analytics/assets/73133191/00bc5357-1060-4c22-b1fe-c1509a1f9977">

after `npm run build`:
<img width="928" alt="Screenshot 2024-06-07 at 2 04 15 PM" src="https://github.com/vercel/analytics/assets/73133191/424d2ca0-0379-439a-b5d9-9090314bae84">

**Comment by tobiaslins** [comment]
Hey! 
Vercel Analytics only works when deployed on Vercel (or when running dev).

**Comment by mitchuman** [comment]
Ok I see it running now when I deploy on the live branch. TY
