### ISSUE TITLE
404 Not Found: _vercel/insights/script.js

### ISSUE THREAD

**Issue by matthew-t3** [vercel/analytics#147]
I have a NextJS app running on Vercel with domain: https://somedomain.com. We have a partner client with an app with domain https://thirdpartydomain.com. They proxy the requests whenever the user visits https://thirdpartydomain.com/app.

But somehow vercel analytics returns 404 when they call https://thirdpartydomain.com/_vercel/insights/script.js even if they proxy the requests. I've tried visiting https://somedomain.com/_vercel/insights/script.js and it works.

**Comment by tobiaslins** [comment]
hi!
If they proxy to `https://thirdpartydomain.com/app` the script will be at `https://thirdpartydomain.com/app/_vercel/insights/script.js`

Also the page will need to customize the `endpoint` location where the script sends event to 

I think this also needs to be `endpoint='/app/_vercel/insights'` in this case

**Comment by matthew-t3** [comment]
This props `endpoint='/app/_vercel/insights` is passed to the `Analytics` component right?

**Comment by tobiaslins** [comment]
yes!

**Comment by matthew-t3** [comment]
Cool, thank you.
