### ISSUE TITLE
Add Usage Guide for @vercel/analytics Exports in next and server Environments

### ISSUE THREAD

**Issue by ohprettyhak** [vercel/analytics#150]
Currently, there is no guide for using `@vercel/analytics` with `next` and `server` environments. The package [exports options](https://github.com/vercel/analytics/blob/main/packages/web/package.json) for `react`, `next`, and `server`, yet the official documentation only covers importing `Analytics` from `@vercel/analytics/react`.

In the [vercel/speed-insights](https://github.com/vercel/speed-insights) repository, packages are defined according to specific frameworks. If the exports in `@vercel/analytics` are indeed designed to support framework-specific environments, adding usage guides for each environment would be highly beneficial.

**Comment by feugy** [comment]
Hello @ohprettyhak!

We recently release framework-specific components, including for next, and updated hour [getting started](https://vercel.com/docs/analytics/quickstart#add-the-analytics-component-to-your-app) guide.
I hope it covers what you're looking for!
