### ISSUE TITLE
Error: The @vercel/analytics/astro integration does not work as documented

### ISSUE THREAD

**Issue by acbcdev** [vercel/analytics#159]
Description: I attempted to implement the @vercel/analytics integration in my project using the documentation provided for Astro. However, importing @vercel/analytics/astro results in an error, as it seems this export does not exist in the library.

Steps to Reproduce:

Install the library using npm i @vercel/analytics.
Follow the Astro-specific instructions in the documentation to import the <Analytics /> component from @vercel/analytics/astro.
Run the project with the recommended setup.
The error occurs because the @vercel/analytics/astro module is not available.
Expected Behavior: The integration should allow me to import and use the <Analytics /> component from @vercel/analytics/astro as described in the documentation.

Actual Behavior: An error is thrown indicating that @vercel/analytics/astro is not a valid export from the library. Additionally, analytics are not being activated.

Environment:

Library version: 1.3.1
Node.js version: v20.18.0
Framework: Astro 4.16.13
Operating System: Fedora Linux 41
astro vercel: 7.8.2
Additional Context/Screenshots: 
![image](https://github.com/user-attachments/assets/af630a97-0dd2-446e-97f1-2bf2e67cf06b)

```import { defineConfig } from "astro/config";
import tailwind from "@astrojs/tailwind";
import vercel from "@astrojs/vercel/serverless";
export default defineConfig({
	site: "https://acbc.dev:",
	output: "server",
	integrations: [
		tailwind({
			nesting: true,
		}),
		vercel({ webAnalytics: { eneble: true } }),
	],
});
```
It seems there is a discrepancy between the documentation and the actual implementation of the library. Could you confirm if the Astro integration is available or if the documentation needs to be updated?

**Comment by feugy** [comment]
Hello @acbcdev 
Indeed, our [documentation](https://vercel.com/docs/analytics/quickstart#add-the-analytics-component-to-your-app) contains instruction for the latest version of our package: 1.4.0

<img width="817" alt="image" src="https://github.com/user-attachments/assets/dc2b32d6-b062-4b28-8a90-96da12999810">


I you use 1.3.x, then you have to use the astro adapter.
In this case, there's a typo in the snippet you've shared:
```js
vercel({ webAnalytics: { eneble: true } }),
```
should instead be: 
```js
vercel({ webAnalytics: { enable: true } }),
```

**Comment by acbcdev** [comment]
thanks
