### ISSUE TITLE
`script.js` trying to `POST` to `/_vercel/insights/view` and receiving `404`

### ISSUE THREAD

**Issue by filipedeschamps** [vercel/analytics#16]
Is this expected? Views on my Analytics are near zero, and I haven't made any deploy on my side.

<img width="863" alt="image" src="https://user-images.githubusercontent.com/4248081/200888871-41973eaf-64a5-4c4b-8149-ee743d179ec5.png">

https://www.tabnews.com.br
https://www.tabnews.com.br/_vercel/insights/view

**Comment by tobiaslins** [comment]
Hey @filipedeschamps 
Thanks for the report!
We just found the issue and deployed a fix - views should be tracked again (once you get the updated script, it might be cached).

**Comment by filipedeschamps** [comment]
Great @tobiaslins thank you! 🤝

**Comment by filipedeschamps** [comment]
Can confirm it's working 👍
