### ISSUE TITLE
Feature request: More events

### ISSUE THREAD

**Issue by martinowren** [vercel/analytics#20]
It would be really nice to have events such as GA4 or FB pixel:
- Add to cart
- Purchase
- Remove from cart
- +++

**Comment by edehlol** [comment]
Yes please, I'm looking for alternative to Google Analytics but the only thing i'm missing with Vercel is that there's no way to track events. 

Would be nice to at least know whether or not adding this feature is on the roadmap anytime soon.

**Comment by timolins** [comment]
Thanks for your feedback! Custom events are on our roadmap and shipping 🔜

**Comment by tobiaslins** [comment]
Vercel Web Analytics went just into General Availability with custom events supported!
Check out our [release post](https://vercel.com/blog/vercel-web-analytics-is-now-generally-available)

Happy to hear what you all think!
