### ISSUE TITLE
Question: More event types, what to expect, when?

### ISSUE THREAD

**Issue by bogy0** [vercel/analytics#23]
Hello,

can you share some estimation/development timeline of what the Vercel users can expect from the Analytics/Audiences feature?
I am struggling now because Splitbee sign-ups are now closed, but Vercel's Audience feature seems limited; for example, only `PageView` events are currently supported.

It seems if I want to start a new project, I need to find another analytics provider to be able to track simple button clicks.
Is it possible that other events will be supported this year and wait a little bit, or is this a much bigger effort?

thanks in advance! ❤️

**Comment by timolins** [comment]
Hi @bogy0. Thanks for your feedback.

Custom events are on top of our list and we expect them to ship within 1-2 months. Hope that works for you :)

**Comment by bogy0** [comment]
That's great, thanks for sharing this @timolins! really appreciate the transparency!

Another useful feature is of course User Properties.
But I can also say a better, more customizable date-range / datepicker addition to Vercel's Audience page would be nice thing too.
I am also curious that by adding Custom Events feature to Vercel dashboard does that mean that it will contain Splitbee User View dashboard?
