### ISSUE TITLE
Refused to execute script

### ISSUE THREAD

**Issue by alex289** [vercel/analytics#4]
I just added this to my site but when I visit it this error gets logged:
`Refused to execute script from 'https://alexanderkonietzko-84q9dz1ke-alex289.vercel.app/va/script.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`

Does this happen because I have X-Content-Type-Options: nosniff enabled?

[Here is my repo for more information](https://github.com/alex289/Portfolio)

**Comment by chriswdmr** [comment]
Thanks for reaching out! 
It seems like you haven't redeployed after you enabled the feature on the Vercel dashboard.

Please make sure you:
1. Enable the feature on the Vercel dashboard
2. Install the package based on the instructions
3. Redeploy your app

Once you redeployed after enabling the feature, the route `/va/script.js` will become available on your deployment

**Comment by alex289** [comment]
I redeployed but still the same error

**Comment by ghoshnirmalya** [comment]
@chriswdmr I'm getting the same error even after deployment. I'm using the following versions:

```json
"@vercel/analytics": "0.1.3",
"next": "12.1.4",
```

Can you please re-open this issue?

**Comment by alex289** [comment]
> @chriswdmr I'm getting the same error even after deployment. I'm using the following versions:
> 
> ```json
> "@vercel/analytics": "0.1.3",
> "next": "12.1.4",
> ```
> 
> Can you please re-open this issue?

I still have this error too but I don’t have the permission to reopen it sorry

**Comment by tobiaslins** [comment]
@ghoshnirmalya can you please share a deployment URL with us? When was your last redeployment?

@alex289 I see your production deployment already exposes `https://alexanderkonietzko.vercel.app/va/script.js` for you, so resolved?

**Comment by alex289** [comment]
I did not check if it was resolved after this but if it is I can say it's resolved for me

**Comment by ghoshnirmalya** [comment]
@tobiaslins You can check out https://rapidapi.com/guides/categories/graphql. The last deployment was 4 days ago.

**Comment by tobiaslins** [comment]
@ghoshnirmalya I can't see the deployment url (vercel.sh) easily because the /guides thing is proxied right?
Can you just try redeploying and see if it works? If not please send me the deployment url (ending with `.vercel.sh`)
Thanks :)

**Comment by tobiaslins** [comment]
@ghoshnirmalya I just found out that you're proxying the Next.js app and the root is not `rapidapi.com` but `rapidapi.com/guides` right?

**Comment by ghoshnirmalya** [comment]
@tobiaslins That is correct.

**Comment by tobiaslins** [comment]
@ghoshnirmalya Can you tell us more on your proxy setup? It seems like (https://rapidapi.com/guides/va/script.js) is also not available. Could you please send us a deployment url (ending with `.vercel.sh`)? Thanks!

**Comment by ghoshnirmalya** [comment]
@tobiaslins You can use https://devrel-stack-guides.vercel.app/guides.
