### ISSUE TITLE
ReferenceError: _reportEvent is not defined

### ISSUE THREAD

**Issue by NathanielHill** [vercel/analytics#41]
Getting these reports intermittently in Sentry after adding `@vercel/analytics/react` to our Next.js app:

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/15079979/216235799-6fa22732-2a39-4f61-a287-3bcaac974983.png">

**Comment by tobiaslins** [comment]
Hey @NathanielHill 
We don't have a function thats called `_reportEvent`. 
This seems to come from something else, maybe a chrome plugin? https://github.com/pulumi/theme/issues/168

Any link you can give me so I can look into it?
