### ISSUE TITLE
My domain/website is showing as a referrer in its own analytics dashboard

### ISSUE THREAD

**Issue by capJavert** [vercel/analytics#42]
This started to happen today where I noticed that my own domain is showing as a referrer in "Top referrers" list. That can't be right?

Don't know what could be a cause, didn't do any obvious changes to my page. 

Also I noticed that when I click on a link to filter by my own domain as referrer it shows zero results, also the links are broken with double protocol string when hovering above those links `https://https//` inside of the same analytics pane. 

If needed I can provide an URL to my project if you wanna check directly on the backend.

**Comment by capJavert** [comment]
Additionally I can see that all referrers in "Top referrers" list in analytics dashboard are showing as `host` eg. `vercel.com`, `twitter.com`, but referrer items for my domain are shown with `https://mydomain.com`, and also there are different entries for different paths eg. `https://mydomain.com/path/a`, `https://mydomain.com/b/path`. Weird 🤔

**Comment by tobiaslins** [comment]
Thanks for the report @capJavert !
We're currently working on that issue, should be fixed soon. I'll let you know.

**Comment by tobiaslins** [comment]
Hey! This should be all back to normal now. Sorry for the inconvenience!
