### ISSUE TITLE
Bug: Internal tsconfig.json shows an error in node_modules right after fresh package install

### ISSUE THREAD

**Issue by nelodev** [vercel/analytics#43]
Hi everyone! 👋

I'm in an Astro project, and after running `npm install @vercel/analytics`, the `node_modules` folder shows an error in the `tsconfig.json file` of this package.

The versions of a few packages that i'm using if it's helpful:

- **Node**: 18.14.0

```json
"astro": "^1.9.2",
"web-vitals": "^3.1.1",
"typescript": "^4.9.4",
"@vercel/analytics": "^0.1.8",
```

This is a bunch of screenshots of the error right after installing this package:

![image](https://user-images.githubusercontent.com/21993984/218894451-fc250986-49a1-4ccf-a005-2a609377b8a9.png)

![image](https://user-images.githubusercontent.com/21993984/218894559-5e35bd14-6254-4b49-ba9f-cdec4fdda274.png)

![image](https://user-images.githubusercontent.com/21993984/218894607-220b4746-af9a-4721-a827-01fe741245e5.png)

Feel free to ask if you have any other doubt about the error and and I'm sorry if the information is very scarce but it is one of my first opened issues! 🦄

**Comment by nelodev** [comment]
I'm gonna close this issue because after reloading the editor a few times, the error has disappeared 😳

**Comment by e10a** [comment]
> I'm gonna close this issue because after reloading the editor a few times, the error has disappeared 😳

I appreciate your post. It saved me from going down a rabbit hole. Thank you so much!
