### ISSUE TITLE
My analytics aren't working, is my HOC the main reason?

### ISSUE THREAD

**Issue by zavbala** [vercel/analytics#47]
Hello fellas, a few days ago I deployed my [Project](https://sargabot.vercel.app), but seems analytics don't work. If you try to open the debugger options, you can't see the script at `/_vercel/insights/script.js`

The only thing that maybe is causing trouble could be the `appWithTranslation` 🤔      

![code](https://user-images.githubusercontent.com/95885060/219440513-19434060-db2a-46cb-b7a3-6f8aeae8378e.png)

Of course, Vercel is waiting for:
![image](https://user-images.githubusercontent.com/95885060/219442502-e91a5fa4-fe94-4650-808e-7ca28ad1aa39.png)

**Comment by tobiaslins** [comment]
Hey @zavbala 

It seems like you enabled Analytics after you redeployed the project. Can you try redeploying to production and check if this resolves your issue?

Thanks! :)
