### ISSUE TITLE
Docs - AdBlockers & reverse proxy?

### ISSUE THREAD

**Issue by AdisonCavani** [vercel/analytics#54]
When your audience is mainly developers and people related to IT industry you are "losing" a lot of data.
A lot of people use **AdBlockers**, (in IT industry more than ~80%, overall ~40%), so this script is blocked - therefore you get no data and visitor count is not accurate.

A solution to this is using some sort of `reverse proxy`.
Is this possible with Vercel Analytics?

PS. This is also accurate to Vercel Insights.

**Comment by tobiaslins** [comment]
Hey!

Audiences already proxies all the traffic through your own domain (same as deployment)
Web Vitals will support this also soon!

**Comment by AdisonCavani** [comment]
Thank you for a quick response.
I'll be waiting for Web Vitals.

![image](https://user-images.githubusercontent.com/76855180/221033795-7e13f78e-d3e9-48ed-a3dc-1b833fc4181b.png)

**Comment by AdisonCavani** [comment]
> Hey!
> 
> Audiences already proxies all the traffic through your own domain (same as deployment) Web Vitals will support this also soon!

@tobiaslins are Web Vitals now proxied?

On my website (Vercel hosting), it's still blocked by ad-blockers because it's from `vitals.vercel-insights.com/v1/vitals` url.

**Comment by tobiaslins** [comment]
@AdisonCavani 

Hey! Not yet, we're actively working on that. Stay tuned for official updates!

**Comment by timolins** [comment]
Good news – the new Speed Insights package now automatically proxies data through your own domain. 

https://vercel.com/docs/speed-insights/migrating-from-legacy#first-party-intake
