### ISSUE TITLE
Loading _vercel/insights/script.js returns 404 with Vite project

### ISSUE THREAD

**Issue by gsantiago** [vercel/analytics#65]
<img width="680" alt="image" src="https://user-images.githubusercontent.com/4365542/230239181-5821d3b1-fb60-4a23-8593-3d3f381aef82.png">

The project uses Vite and you can see the source code here: https://github.com/gsantiago/SereneBreath

I already enabled the analytics on the dashboard and tried a few redeploys after it. I also tried to disabled and re-enable the analytics but it also didn't work.

<img width="521" alt="image" src="https://user-images.githubusercontent.com/4365542/230239324-974560a5-af77-42b1-9893-cb09efcc041e.png">

**Comment by tobiaslins** [comment]
Hey! 
You have enabled Web Vitals Analytics and not Audiences which is required to make this work.
It is a sub tab in the "Analytics" tab.
We're working on improving that experience which should be available soon.

Let me know if that works!

**Comment by gsantiago** [comment]
That's it!

I enabled the audiences, redeployed the project and now it's working!

Thanks!

**Comment by emrecoban** [comment]
> Hey! You have enabled Web Vitals Analytics and not Audiences which is required to make this work. It is a sub tab in the "Analytics" tab. We're working on improving that experience which should be available soon.
> 
> Let me know if that works!
@tobiaslins 
I have been researching for hours to solve this problem, and it turns out the solution was this simple. Please add this explanation to your documentation page.

**Comment by mryechkin** [comment]
> Hey! You have enabled Web Vitals Analytics and not Audiences which is required to make this work. It is a sub tab in the "Analytics" tab. We're working on improving that experience which should be available soon.
> 
> Let me know if that works!

How do I get to this tab? I'm not able to navigate anywhere on the Analytics page:

<img width="1563" alt="Screenshot 2023-05-18 at 10 21 36 PM" src="https://github.com/vercel/analytics/assets/5657181/52dc4ad6-abfe-4afc-b935-5dcb27d14976">

**Comment by AnthonyVNgo** [comment]
@tobiaslins I'm running in to a similar problem

- I'm trying to add analytics to my project
- I've followed the instructiosn on astro's docs and vercels
https://vercel.com/docs/analytics/quickstart
- I've deployed, redeployed, promoted to production, deleted project and re-deployed and nothing has worked.

```
  "dependencies": {
    "@astrojs/react": "^3.0.2",
    "@astrojs/tailwind": "^5.0.0",
    "@astrojs/vercel": "^5.0.1",
    "@types/react": "^18.2.23",
    "@types/react-dom": "^18.2.7",
    "@vercel/analytics": "^1.0.2",
    "astro": "^3.1.4",
    "hamburger-react": "^2.5.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "tailwindcss": "^3.3.3"
  },
```

```
import { defineConfig } from "astro/config";
import vercel from "@astrojs/vercel/serverless";
import tailwind from "@astrojs/tailwind";
import react from "@astrojs/react";

// https://astro.build/config
export default defineConfig({
  integrations: [tailwind(), react()],
  output: "server",
  adapter: vercel({
    webAnalytics: {
      enabled: true,
    },
  }),
});
```
