### ISSUE TITLE
NextJS App won't build with `pnpm`

### ISSUE THREAD

**Issue by StevenLangbroek** [vercel/analytics#69]
Hey folks! I've followed the quickstart instructions, but am presented with this error when building our app with `pnpm` on Github Actions:

![image](https://user-images.githubusercontent.com/296796/234532144-b51c70cf-bca2-4a1c-bf24-eb7d1a912506.png)

What info can I provide to help reproduce this issue?

**Comment by tobiaslins** [comment]
Hey @StevenLangbroek !
Which version of `@vercel/analytics` do you have in your `package.json`?

Thanks :)

**Comment by StevenLangbroek** [comment]
@tobiaslins it's `^1.0.0`, which has resolved to *drumroll* `1.0.0` :D

**Comment by tobiaslins** [comment]
I see you're using `next@13.1.6` and I think at that version there was no support for `"use client"` that was shipped in packages. Can you try to either upgrade to latest Next.js or try wrapping our analytics component before like following:
```
'use client';

import { Analytics } from '@vercel/analytics/react';

export function VercelWebAnalytics(): JSX.Element {
  return (
    <Analytics />
  );
}
```

and in `layout.tsx` use `<VercelWebAnalytics />`

Let me know if that resolves your issue!

**Comment by StevenLangbroek** [comment]
Ahhh that's right yeah, we're a little behind and the migration is a bit painful. Will try the workaround for now, let you know how it goes. Thanks!

**Comment by tobiaslins** [comment]
Hey @StevenLangbroek , is it working now? Thanks!

**Comment by StevenLangbroek** [comment]
@tobiaslins whoops yes it is! Thanks for the assistance
