### ISSUE TITLE
Vercel analytics data much higher than another analytics

### ISSUE THREAD

**Issue by pepelele** [vercel/analytics#80]
Hi, I wonder how Vercel Analytics calculates visitors and pageviews. I test with Vercel and it got 7k visitors and 70k pageviews per day but with Fathom or Google Analytics (the data of both platforms is quite similar) I just got 4k5 visitors and 40k pageviews... why is it so different?

**Comment by tobiaslins** [comment]
Hey! 

Because GA and others are mostly blocked by adblockers and we are not!

This is because Vercel Web Analytics works with an first-party intake (page views are tracked over the same domain as your website)
