### ISSUE TITLE
404 error in nuxt3 about _vercel/insights/script.js

### ISSUE THREAD

**Issue by LawyerKyrie** [vercel/analytics#84]
# Fix:
`Option 1`: In `node_modules/@vercel/analytics/analytics/dist/index.js`, 
- line 81
  - change "_vercel/insights/script.js" with _"https://vercel.com/_vercel/insights/script.js"_

Or better, `option 2`:
- In your project repo 
  - create the folder 
    - "_vercel/insights"
  and 
  - copy the file 
    - _"https://vercel.com/_vercel/insights/script.js"_,
  to
  - "_vercel/insights/script.js"

## Last step
In nuxt3 create the following `plugin`-file:
## ~/plugins/vercel.client.ts
```javascript [~/plugins/vercel.client.ts]
import { inject } from '@vercel/analytics'

export default defineNuxtPlugin((/* nuxtApp */) => {
  // nuxtApp.provide('inject', () => inject() ) // Not working, using return instead.

  return {
    provide: {
      inject: inject()
    }
  }
})

/*
sources:
https://vercel.com/docs/concepts/analytics/quickstart
https://vercel.com/blog/nuxt-analytics-on-vercel
https://nuxt.com/docs/migration/plugins-and-middleware
https://vercel.com/lovkyndig/eleison/analytics // login to activate analytics

Read about the fix in 
https://github.com/vercel/analytics/issues/84
*/
```
My GitHub-repo with this code is here: [Eleison](https://github.com/lovkyndig/eleison)

**Comment by tobiaslins** [comment]
Hey @lovkyndig 

Both proposed solutions are not recommend!
Did you try to follow our instructions from the Nuxt documentation?
https://vercel.com/docs/concepts/analytics/quickstart

Otherwise there is also a Nuxt community package that wraps `@vercel/analytics`.
https://github.com/xanderbarkhatov/nuxt-vercel-analytics
