### ISSUE TITLE
Custom events from routes / SSR

### ISSUE THREAD

**Issue by rsolomon** [vercel/analytics#98]
The documentation for [custom events](https://vercel.com/docs/analytics/custom-events) states:

> It’s important to note that custom events can only be tracked on the client-side. Server-side events are not currently supported by Vercel Web Analytics.

Are server-side custom events on the roadmap? Or would you recommend an alternative approach? I know of a lot of the popular alternatives like Datadog and NewRelic, but I'd love to use a simpler integrated solution.

Thanks for all you folks do!

**Comment by tobiaslins** [comment]
Hey @rsolomon 
Server-side custom events are currently in development. You can already try using them using the beta package.

Find code examples [here](https://github.com/vercel/analytics/blob/serverside-events/apps/nextjs/app/api/serverless/route.ts) in the branch.

But heads up: This is an early access and the API might change before public release.

Let us know what you think

**Comment by tobiaslins** [comment]
Hey again! @rsolomon 

They are out now! :)
https://vercel.com/changelog/track-server-side-custom-events-with-vercel-web-analytics

Let me know what you think!
